version: "3.9"


services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.8.9-management"
    hostname: rabbitmq
    volumes:
      - ./:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      # AMQP protocol port
      - '15672:15672'
      # HTTP management UI

  celeryworker:
    container_name: celeryworker
    hostname: celeryworker
    build: .
    volumes:
      - ./:/app
    command: celery -A core worker -l info
    depends_on:
      - rabbitmq

  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports: 
      - '8000:8000'
    environment:
      - DEBUG=True     
  