# Generated by Django 3.2.9 on 2021-12-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211216_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='accounts/avatar/1.jpg', upload_to=''),
        ),
    ]
